In [5]:
###Numpy - Numerical Python###


In [6]:
import numpy as np

In [8]:
arr0 = np.array(15)
print(arr0)
print(type(arr0))
print("Dimension : ",arr0.ndim)

15
<class 'numpy.ndarray'>
Dimension :  0


In [11]:
arr1 = np.array([15,16,17,18,19])
print(arr1)
print(type(arr1))
print("Dimension : ",arr1.ndim)

[15 16 17 18 19]
<class 'numpy.ndarray'>
Dimension :  1


In [34]:
arr2 = np.array([[15,16,17,18,19],[15,16,17,18,19],[15,16,17,18,19]])
print(arr2)
print(type(arr2))
print("Dimension : ",arr2.ndim)

[[15 16 17 18 19]
 [15 16 17 18 19]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
Dimension :  2


In [13]:
arr3 = np.array([[[15,16,17,18,19],[15,16,17,18,19]],[[15,16,17,18,19],[15,16,17,18,19]]])
print(arr3)
print(type(arr3))
print("Dimension : ",arr3.ndim)

[[[15 16 17 18 19]
  [15 16 17 18 19]]

 [[15 16 17 18 19]
  [15 16 17 18 19]]]
<class 'numpy.ndarray'>
Dimension :  3


In [14]:
###Index and Slicing of Arrays###

In [16]:
arr0

array(15)

In [17]:
arr1

array([15, 16, 17, 18, 19])

In [21]:
arr1[1:4]

array([16, 17, 18])

In [22]:
arr1[1:5:3]

array([16, 19])

In [35]:
arr2

array([[15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19]])

In [25]:
arr2[1,2]

17

In [36]:
arr2[0:2,2:4]

array([[17, 18],
       [17, 18]])

In [29]:
arr2[:2,3:4]

array([[18],
       [18]])

In [43]:
arr2[:,1:4:3]

array([[16],
       [16],
       [16]])

In [38]:
arr2

array([[15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19]])

In [44]:
arr2[1,4:2:2]

array([], dtype=int32)