Checking the Data Type of an Array

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [5]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


Creating Arrays With a Defined Data Type

In [8]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [10]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


Converting Data Type on Existing Arrays

In [13]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [15]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [17]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
