Generate Random Number

In [11]:
from numpy import random

x = random.randint(100)

print(x)

1


Generate Random Float

In [14]:
x = random.rand()
print(x)

0.7088123768871241


Generate Random Array

In [17]:
x=random.randint(100, size=(5))
print(x)

[12 64 71 53 13]


In [19]:
x = random.randint(100, size=(3, 5))
print(x)

[[43 17 32  7 95]
 [21 74 63 58 27]
 [ 9 70 11 74  5]]


In [21]:
x = random.rand(5)
print(x)

[0.90344797 0.74435431 0.81263283 0.46983849 0.83044609]


In [25]:
x = random.rand(3, 5)
print(x)

[[0.25605957 0.81090356 0.86609215 0.76106077 0.27541842]
 [0.21139326 0.47504415 0.27329117 0.02444811 0.89355504]
 [0.75947935 0.97879673 0.06719304 0.22271793 0.46411689]]


Generate Random Number From Array

In [28]:
x = random.choice([3, 5, 7, 9])
print(x)

9


In [30]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[5 3 9 5 7]
 [9 9 3 5 3]
 [5 5 3 7 5]]
