# Random Data Distribution

In [3]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 7 7 7 7 5 7 7 7 7 5 7 7 5 5 5 7 7 3 7 5 3 7 7 5 5 3 5 7 7 5 7 5 7 7 7 7
 7 7 7 7 5 7 7 7 7 5 7 7 3 7 5 7 5 5 3 7 5 7 7 7 3 7 5 5 5 3 7 7 7 3 7 7 5
 7 7 5 5 7 5 7 5 7 7 7 7 7 7 7 5 7 7 5 7 7 7 7 7 7 7]


In [5]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 5 7 5 5]
 [7 5 7 7 5]
 [5 7 7 5 7]]
