In [15]:
    # NumPy Trigonometric Functions

import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [17]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [19]:
# Convert Degrees Into Radians

import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [21]:
# Radians to Degrees

import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [23]:
# Finding Angles

import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [25]:
# Angles of Each Value in Arrays

import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [27]:
# Hypotenues

import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
