#  Numpy Universal Function

In [3]:
import numpy as np

In [5]:
def add(a,b):
        return a+b
print(type(add))

<class 'function'>


In [8]:
print(type(np.add))

<class 'numpy.ufunc'>


In [10]:
add_u = np.frompyfunc(add,2,1)
print(type(add_u))

<class 'numpy.ufunc'>


In [12]:
# add
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.add(arr1,arr2)
arr3

array([ 6,  8, 10, 12])

In [14]:
# subtract
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.subtract(arr1,arr2)
arr3

array([-2, -2, -2, -2])

In [16]:
# mulitply
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.multiply(arr1,arr2)
arr3

array([ 8, 15, 24, 35])

In [18]:
# mod
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.remainder(arr2,arr1)
arr3

array([0, 2, 2, 2])

In [20]:
# divmod
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.divmod(arr2,arr1)
arr3

(array([2, 1, 1, 1]), array([0, 2, 2, 2]))

In [22]:
# absolute
arr1 = np.array([2,-3,4,-5])
# arr2 = np.array([4,5,6,7])

arr3 = np.abs(arr1)
arr3

array([2, 3, 4, 5])

# Numpy Logarithmic Fucntions

In [26]:
# log2

base = np.log2(arr1)
base

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_8320\2525474654.py:3: RuntimeWarning: invalid value encountered in log2
  base = np.log2(arr1)


array([ 1., nan,  2., nan])

In [28]:
# log10
base = np.log10(arr1)
base

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_8320\141745994.py:2: RuntimeWarning: invalid value encountered in log10
  base = np.log10(arr1)


array([0.30103   ,        nan, 0.60205999,        nan])

In [30]:
# loge
base = np.log(arr1)
base

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_8320\1740743618.py:2: RuntimeWarning: invalid value encountered in log
  base = np.log(arr1)


array([0.69314718,        nan, 1.38629436,        nan])